import "./globals.css";
import { Inter } from "next/font/google";
import Head from 'next/head';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <head>
        <script
          src="https://static.nid.naver.com/js/naveridlogin_js_sdk_2.0.2.js"
          async
        ></script>



        <script
          src="https://developers.kakao.com/sdk/js/kakao.js"
          async
        ></script>

<script src="https://accounts.google.com/gsi/client" async></script>
<script src="https://apis.google.com/js/platform.js?onload=init" async defer></script>
 {/* <meta name="google-signin-scope" content="profile email"></meta> */}
        {/* <meta
          name="google-signin-client_id"
          content={`${process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}.apps.googleusercontent.com`}
        ></meta>
        <script src="https://apis.google.com/js/platform.js" async></script>  */}
      </head>

      <html lang="en">
{/* <script src="https://accounts.google.com/gsi/client" async defer></script> */}
        <body suppressHydrationWarning={true}>{children}</body>
        
      </html>
    </>
  );
}
